#!/bin/sh
# M2 bootstrap — dynamic database credentials.
# OpenBao gets admin access to Postgres, and from then on creates a brand-new,
# short-lived Postgres user every time someone with permission asks for one.
#
# Run from the project root:   docker compose run --rm bootstrap /bootstrap/m2-setup.sh
# Commands follow the OpenBao docs: Secrets engines → Databases → PostgreSQL (v2.7.x).
set -eu
CLI="${CLI:-bao}"   # "bao" for OpenBao, "vault" for HashiCorp Vault — same commands

echo "== M2 bootstrap using: $CLI"

# --- 1. Turn on the database secrets engine (once) -----------------------------
if ! $CLI secrets list -format=json | grep -q '"database/"'; then
  echo "-- enabling database secrets engine"
  $CLI secrets enable database
fi

# --- 2. Tell OpenBao how to reach Postgres, and with which admin login ----------
# {{username}} / {{password}} are filled in by OpenBao from the two fields below.
# "postgres" is the hostname of the Postgres container on the Docker network.
# LAB ONLY: we hand OpenBao the superuser. In production you give it a dedicated
# admin role and then run `$CLI write -f database/rotate-root/supportdesk`, so that
# afterwards ONLY OpenBao knows that password (we skip it here: pgAdmin uses it).
echo "-- configuring connection supportdesk"
$CLI write database/config/supportdesk \
  plugin_name="postgresql-database-plugin" \
  allowed_roles="kouventa-app" \
  connection_url="postgresql://{{username}}:{{password}}@postgres:5432/supportdesk?sslmode=disable" \
  username="postgres" \
  password="postgres-dev-only" \
  password_authentication="scram-sha-256"

# --- 3. A role: the SQL OpenBao runs to create each temporary user ---------------
# {{name}}, {{password}}, {{expiration}} are generated by OpenBao per request.
# VALID UNTIL makes Postgres itself reject the password after expiry (a second lock);
# when the lease ends, OpenBao also revokes the privileges and DROPs the user.
# default_ttl 2m / max_ttl 10m are short on purpose so you can watch it expire.
echo "-- writing role kouventa-app"
$CLI write database/roles/kouventa-app \
  db_name="supportdesk" \
  creation_statements="CREATE ROLE \"{{name}}\" WITH LOGIN PASSWORD '{{password}}' VALID UNTIL '{{expiration}}'; GRANT CONNECT ON DATABASE supportdesk TO \"{{name}}\"; GRANT USAGE ON SCHEMA public TO \"{{name}}\";" \
  default_ttl="2m" \
  max_ttl="10m"

# --- 4. Re-apply the app policy (it now also allows database/creds/kouventa-app) --
echo "-- updating policy kouventa-app"
$CLI policy write kouventa-app /bootstrap/policies/kouventa-app.hcl

echo "== done. Get a credential:  read database/creds/kouventa-app  (UI console)"
